### ISSUE TITLE
Webpack Dev Server Not Working

### ISSUE THREAD

**Issue by swashcap** [bananaoomarang/isomorphic-redux#8]
In following along with [your tutorial](https://medium.com/@bananaoomarang/handcrafting-an-isomorphic-redux-application-with-love-40ada4468af4) I can’t seem to get the Webpack Dev Server to work. I `git clone`-d this repo, installed all the modules and tried running it on my machine. Visiting _localhost:8080_ results in an “ERR_EMPTY_RESPONSE” in Chrome. Webpack builds the bundle just fine, but here’s also no error output in from Webpack Dev Server in the console. Thoughts?
- OS: OS X 10.10.5
- Browser: Google Chrome 44
- Node: v3.1.0
- NPM: 2.13.3

**Comment by bananaoomarang** [comment]
I'm not sure why this is happening to you I'm afraid. I just tried a fresh `npm i` with the latest and it works in Chrome 46 and Firefox 42. I have the same Node and NPM versions, but am on Linux. Best advice would be to try `rm -rf node_modules` then `npm install` again (I've fixed strange errors that way before), and I'll have a think.

**Comment by swashcap** [comment]
Thanks for the response. I’m working from the beginning of the tutorial and pushing to https://github.com/swashcap/handcrafted-redux. It seems to work fine until:

> Now we can start our app with npm run dev (instead of npm start) and Webpack will serve our client a bundle.js, so it can do it’s own routing from here-on-out.

I’m getting no response at _localhost:8080_. Guessing the problem lies in the Webpack config.

**Comment by swashcap** [comment]
_Ah._ There’s a bunch of errors when I re-installed everything. Looks like nan and some node-gyp stuff.

**Comment by swashcap** [comment]
Okay, switched to Node **v0.12.7**. Everything installs fine, but the dev server still isn’t working at _localhost:8080_. Very strange indeed. Perhaps I should spin up a linux virtual machine.

**Comment by bananaoomarang** [comment]
This is very odd. You could try binding to `0.0.0.0` instead of `localhost` in the config like:

`'webpack-dev-server/client?http://0.0.0.0:8080/',`

&

`'*': 'http://0.0.0.0:' + (process.env.PORT || 3000)`

I guess the issue must be a difference somewhere in our network set ups.

EDIT: [This](https://github.com/webpack/webpack-dev-server/issues/183) might be relevant, you could try going to `127.0.0.1:8080` instead of `localhost:8080`

**Comment by alexw668** [comment]
Cloned the repo, ran 'npm i' to grab depended libs, and got the following errors when trying to run 'npm run dev':
...

> NODE_PATH=$NODE_PATH:./shared node --harmony .

 70% 1/1 build modulesevents.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:81:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:99:10)

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE
npm ERR! isomorphic-redux@1.0.0 dev: `npm run start & webpack-dev-server --progress --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the isomorphic-redux@1.0.0 dev script 'npm run start & webpack-dev-server --progress --color'.
npm ERR! This is most likely a problem with the isomorphic-redux package,
npm ERR! not with npm itself.
...

I am on OSX 10.10.5. 

Any ideas why?

Thanks!

**Comment by bananaoomarang** [comment]
Looks like something's already bound to that port on your machine it's possible the server is already running (try 'killall node' then 'npm run dev' again). Either that or try changing the port in server.jsx or the webpack.config.

**Comment by alexw668** [comment]
Ah, that's it! Thanks.

**Comment by alexw668** [comment]
Got the same error again after seeing "webpack: bundle is now VALID" in log after hitting the page via http://localhost:3000. 

Strange.

**Comment by cr0cK** [comment]
@alexw668 Check if your port 3000 is free (`sudo netstat -nltp`)
If not, you can try on an another port: `PORT=8081 npm run dev`
then go to localhost:8081.

Have a look to my PR too if you experience some issues with the webpack path.

**Comment by slonofanya** [comment]
And what about it?

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart isomorphic-redux@1.0.0
6 info start isomorphic-redux@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info isomorphic-redux@1.0.0 Failed to exec start script
9 verbose stack Error: isomorphic-redux@1.0.0 start: `NODE_PATH=$NODE_PATH:./shared node --harmony .`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid isomorphic-redux@1.0.0
11 verbose cwd /Users/slava/Applications/web/test/test_redux/isomorphic-redux
12 error Darwin 14.5.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
14 error node v4.0.0
15 error npm  v2.14.2
16 error code ELIFECYCLE
17 error isomorphic-redux@1.0.0 start: `NODE_PATH=$NODE_PATH:./shared node --harmony .`
17 error Exit status 1
18 error Failed at the isomorphic-redux@1.0.0 start script 'NODE_PATH=$NODE_PATH:./shared node --harmony .'.
18 error This is most likely a problem with the isomorphic-redux package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     NODE_PATH=$NODE_PATH:./shared node --harmony .
18 error You can get their info via:
18 error     npm owner ls isomorphic-redux
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by dev0x10** [comment]
I had similar issue on Mac

```
Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at net.js:1376:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! react-webpack-babel@0.0.2 dev: `webpack-dev-server --progress --profile --colors --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-webpack-babel@0.0.2 dev script 'webpack-dev-server --progress --profile --colors --hot'.
npm ERR! This is most likely a problem with the react-webpack-babel package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --progress --profile --colors --hot
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-webpack-babel
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zer0config/Git/React/react-webpack-babel/npm-debug.log
```

But running with command :
**sudo npm run dev** 
fix the problem

**Comment by bananaoomarang** [comment]
If you need to run node as root that means there's something wrong with your module permissions, probably an errant `sudo npm install`.

Anyway, problems with the dev server should be fixed (/changed) by the [pull request](https://github.com/bananaoomarang/isomorphic-redux/pull/21)  I just merged/

**Comment by AlexandraKlein** [comment]
Add the following to the top of your libs/parts.js:  

`const webpack = require('webpack');`

**Comment by ruofeng086** [comment]
I had similar issue on Mac
` 70% 1/1 build modulesevents.js:154
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:77:26)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v5.8.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! bbs@1.0.0 dev: `cross-env NODE_ENV=development webpack-dev-server --progress --hot --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bbs@1.0.0 dev script 'cross-env NODE_ENV=development webpack-dev-server --progress --hot --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bbs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development webpack-dev-server --progress --hot --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bbs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bbs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ruofeng/Documents/proejct/kudai/bbs/npm-debug.log`

**Comment by tarkanlar** [comment]
sudo npm start solved my issue too thanks @dev0x10

**Comment by kishorebovi** [comment]
I'm getting following error. Can anyone tell me whats wrong.

> myreact@1.0.0 start C:\Users\Kishore\Desktop\reactApp
> webpack-dev-server --hot

'webpack-dev-server' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! myreact@1.0.0 start: `webpack-dev-server --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myreact@1.0.0 start script 'webpack-dev-server --hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the myreact package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs myreact
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls myreact
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Kishore\Desktop\reactApp\npm-debug.log

**Comment by PavelHasala** [comment]
@tarkanlar this solves my problem only half way, as server will now start, but it wont connect to server
`GET http://localhost:1337/ 404 (Not Found)`

**Comment by rj291991** [comment]
am getting the same error on window.




Failed at the reactapp@1.0.0 start script 'webpack-dev-server --hot'.
Make sure you have the latest version of node.js and npm installed.
If you do, this is most likely a problem with the reactapp package,
not with npm itself.
Tell the author that this fails on your system:
    webpack-dev-server --hot
You can get information on how to open an issue for this project with
    npm bugs reactapp
Or if that isn't available, you can get their info via:
    npm owner ls reactapp
There is likely additional logging output above.
Windows_NT 6.1.7601
argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs
node v6.10.0
npm  v3.10.10
code ELIFECYCLE

reactapp@1.0.0 start: `webpack-dev-server --hot`
Exit status -4058



0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle reactapp@1.0.0~prestart: reactapp@1.0.0
6 silly lifecycle reactapp@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle reactapp@1.0.0~start: reactapp@1.0.0
8 verbose lifecycle reactapp@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle reactapp@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\reactApp\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\Doctrine extensions for PHP\;C:\Program Files (x86)\ZipGenius 6\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\nodejs\;C:\Program Files\MongoDB\Server\3.4\bin;C:\Users\Administrator\AppData\Roaming\npm
10 verbose lifecycle reactapp@1.0.0~start: CWD: D:\reactApp
11 silly lifecycle reactapp@1.0.0~start: Args: [ '/d /s /c', 'webpack-dev-server --hot' ]
12 info lifecycle reactapp@1.0.0~start: Failed to exec start script
13 verbose stack Error: reactapp@1.0.0 start: `webpack-dev-server --hot`
13 verbose stack spawn C:\Windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.4\bin ENOENT
13 verbose stack     at exports._errnoException (util.js:1022:11)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
13 verbose stack     at onErrorNT (internal/child_process.js:359:16)
13 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
13 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
14 verbose pkgid reactapp@1.0.0
15 verbose cwd D:\reactApp
16 error Windows_NT 6.1.7601
17 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 error node v6.10.0
19 error npm  v3.10.10
20 error file C:\Windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.4\bin
21 error path C:\Windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.4\bin
22 error code ELIFECYCLE
23 error errno ENOENT
24 error syscall spawn C:\Windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.4\bin
25 error reactapp@1.0.0 start: `webpack-dev-server --hot`
25 error spawn C:\Windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.4\bin ENOENT
26 error Failed at the reactapp@1.0.0 start script 'webpack-dev-server --hot'.
26 error Make sure you have the latest version of node.js and npm installed.
26 error If you do, this is most likely a problem with the reactapp package,
26 error not with npm itself.
26 error Tell the author that this fails on your system:
26 error     webpack-dev-server --hot
26 error You can get information on how to open an issue for this project with:
26 error     npm bugs reactapp
26 error Or if that isn't available, you can get their info via:
26 error     npm owner ls reactapp
26 error There is likely additional logging output above.
27 verbose exit [ 1, true ]

**Comment by MusOmar** [comment]
First time running npm run dev 
it was fine but when i exit, and try again. gives error. but the port is still functioning 
if i open in the browser like:

localhost:8080
localhost:3000

**Comment by MusOmar** [comment]
if you have issue port 8080 after running second time npm run dev,
this is the issue. it is running the task manager so when you kill that port, you can use it again 
or you can use direct in the search bar of your browser.
![24 hot module replacement config part 6](https://user-images.githubusercontent.com/6962649/34800108-b83f882e-f662-11e7-897a-32f94deab9d9.JPG)

**Comment by stilltorik** [comment]
@MusOmar 
I am having the same issue you are having. Your workaround works, but I'm looking for a cleaner solution. Is there a way to end that process when the command ends?

**Comment by MusOmar** [comment]
@stilltorik if you are windows, i don't have solution for you bro! 
but the tutorial was using Mac so he left his cmd open with port 8080 running and open another cmd which he was using for update the content by running the command npm run dev without error.

**Comment by stilltorik** [comment]
@MusOmar
I'll try to find something. Thanks for the workaround though!
